controllers/OnlinesliderController.php
<?php

namespace app\controllers;
use Yii;
use yii\web\Controller;
use \app\models\Slider;

class OnlinesliderController extends \yii\web\Controller
{
    public function actionIndex()
    {
    	 $searchModel = new \app\models\SliderSearch();
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
$dataProvider->query->andFilterWhere(['status'=>1]);
        return $this->render('index',[
        	'searchModel'=>$searchModel,
        	'dataProvider'=>$dataProvider,
        ]);
    }

    public function actionAddslider()
    {
    	$model = new \app\models\Slider();

    if ($model->load(Yii::$app->request->post())) {
           $model->file = \yii\web\UploadedFile::getInstance($model, 'file');
           $model->file1 = \yii\web\UploadedFile::getInstance($model, 'file1');
           $model->file2 = \yii\web\UploadedFile::getInstance($model, 'file2'); 
           $model->file3 = \yii\web\UploadedFile::getInstance($model, 'file3'); 
         $model->files = \yii\web\UploadedFile::getInstance($model, 'files');
         if ($model->file ) {
$imagetoload = 'header'.time();

if( $model->file->saveAs('image/slider/' . $imagetoload . '.' . $model->file->extension)) 
{
$model->slider_image = $imagetoload . '.' . $model->file->extension; 
}
} 
        if ($model->files ) {
$imagetoload = 'slider'.time();

if( $model->files->saveAs('image/slider/' . $imagetoload . '.' . $model->files->extension)) 
{
$model->product_image1 = $imagetoload . '.' . $model->files->extension; 
}
}
 if ($model->file1 ) {
$imagetoload = 'sliders'.time();

if( $model->file1->saveAs('image/slider/' . $imagetoload . '.' . $model->file1->extension)) 
{
$model->product_image2 = $imagetoload . '.' . $model->file1->extension; 
}
}
 if ($model->file2 ) {
$imagetoload = 'sliderss'.time();

if( $model->file2->saveAs('image/slider/' . $imagetoload . '.' . $model->file2->extension)) 
{
$model->product_image3 = $imagetoload . '.' . $model->file2->extension; 
}
}
 if ($model->file3 ) {
$imagetoload = 'slidersss'.time();

if( $model->file3->saveAs('image/slider/' . $imagetoload . '.' . $model->file3->extension)) 
{
$model->product_image4 = $imagetoload . '.' . $model->file3->extension; 
}
}
        
        $model->save();
        return $this->redirect(['index']);
    } else {
        return $this->render('addslider', [
            'model' => $model,
            
        ]);
    }
    }
    public function actionSliderupdate($id)
    {
        $model=\app\models\Slider::findOne(['id'=>$id]);
            if($model->load(Yii::$app->request->post())){
        $model->save();
    return $this->redirect(['index']);
    } else {
    return $this->render('addslider', [
    'model' => $model,
    ]);
    }
    }
    public function actionSliderdelete($id)
    {
    	$model=\app\models\Slider::findOne(['id'=>$id]);
$model->status=0;
$model->save();
return $this->redirect(['index']);
    }
    public function actionViewslider($id)
    {
    	$model= \app\models\Slider::findOne(['id'=>$id]);
        return $this->render('viewslider',['model'=>$model]);
    }


}

views/onlineslider/addslider.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\file\FileInput;
/* @var $this yii\web\View */
/* @var $model app\models\Slider */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="card">
    <div class="back-btn">
        <a href="<?=Yii::$app->homeUrl ?>?r=/onlineslider/index"><button class="btn">Back</button></a>
    </div>
    <div class="add-title">
        <h2>Add Slider</h2>
    </div>
<div class="slider-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?= $form->field($model, 'product_name')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
             <?= $form->field($model, 'product_price')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
             <?= $form->field($model, 'product_brand')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link1')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link2')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
             <?= $form->field($model, 'affiliate_link3')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link4')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_price1')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_price2')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
</div>
<div class="row">
    
    <div class="col-md-3">
        <div class="form-group">
     <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'files')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/slider/" . $model->product_image1;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/slider/".$model->product_image1 ?>" />
    <?php
}
echo $form->field($model,'files')->fileInput(['maxlength'=> true]);
}
    
    ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file1')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/slider/" . $model->product_image2;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/slider/".$model->product_image2 ?>" />
    <?php
}
echo $form->field($model,'file1')->fileInput(['maxlength'=> true]);
}
    
    ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
             <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file2')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/slider/" . $model->product_image3;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/slider/".$model->product_image3 ?>" />
    <?php
}
echo $form->field($model,'file2')->fileInput(['maxlength'=> true]);
}
    
    ?>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file3')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/slider/" . $model->product_image4;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/slider/".$model->product_image4 ?>" />
    <?php
}
echo $form->field($model,'file3')->fileInput(['maxlength'=> true]);
}
    
    ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/slider/" . $model->slider_image;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/slider/".$model->slider_image ?>" />
    <?php
}
echo $form->field($model,'file')->fileInput(['maxlength'=> true]);
}
    
    ?>
           
        </div>
    </div>
    
    
</div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
           
            <label>Sub Description</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'product_subdescrip',
    'options' => [
        // html attributes
        'id'=>'slider2'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
        </div>
        <div class="form-group">
           
            <label>Key Specification</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'detail',
    'options' => [
        // html attributes
        'id'=>'slider4'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
        </div>
    </div>
    </div>
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
           
            <label>Description for Products</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'long_descrip',
    'options' => [
        // html attributes
        'id'=>'slider3'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
        </div>
    </div>
</div>



    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div>

views/onlineslider/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NoticesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Products';

?>


<!-- code part of the slider part -->
    <div class="list-grid">
    
 	<div class="add-title">
        <h2>Slider </h2>
    </div>
    <hr>
    <div class=" col-md-12" >
       
         <p class="edit-data" >
    <?= Html::a('Create Slider', ['addslider'], ['class' => 'btn ']) ?>
  </p>
        <div class="list-table" >
            <div class="sub-list-title">
            <h3>List of Sliders </h3>
            </div> 
          
      <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'title',
            'product_name',
            'product_price',
            'product_brand',
            //'product_subdescrip:ntext',
            //'affiliate_link1',
            //'affiliate_link2',
            //'affiliate_link3',
            //'affiliate_link4',
            //'long_descrip:ntext',
            //'detail:ntext',
            //'slider_image',
            //'product_image1',
            //'product_image2',
            //'product_image3',
            //'product_image4',
            //'status',


            ['class' => 'yii\grid\ActionColumn','contentOptions'=>['style'=>'width:165px'] ,'template' => '{view} {update} {delete}',

            'buttons' => [
                'view' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>View</span>", ['onlineslider/viewslider','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
                            'update' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>Update</span>", ['onlineslider/sliderupdate','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
                            'delete' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>Delete</span>", ['onlineslider/sliderdelete','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
         
            ]
        ],


        ],
    ]); ?>
        </div>
    </div>

</div>
<!-- end code part of the slider part -->

views/onlineslider/viewslider.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Slider */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['sliderupdate', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['sliderdelete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'product_name',
            'product_price',
            'product_brand',
            'product_subdescrip:ntext',
            'affiliate_link1',
            'affiliate_link2',
            'affiliate_link3',
            'affiliate_link4',
            'long_descrip:ntext',
            'detail:ntext',
            'slider_image',
            'product_image1',
            'product_image2',
            'product_image3',
            'product_image4',
            'status',
        ],
    ]) ?>

</div>