controllers/OnlineproductController.php
<?php

namespace app\controllers;
use Yii;
use \app\models\CategoriesSubmenu;
use yii\web\Controller;
use app\models\Product;


class OnlineproductController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $searchModel = new \app\models\ProductSearch();
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
$dataProvider->query->andFilterWhere(['status'=>1]);

return $this->render('index', [
'searchModel' => $searchModel,
'dataProvider' => $dataProvider,

]);
    }

   public function actionSubcat() {
    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    if (isset(Yii::$app->request->post()['depdrop_parents'])) {
        $parents = Yii::$app->request->post('depdrop_parents');
        if ($parents != null) {
            $cat_id = $parents[0];
            return [
                'output' => CategoriesSubmenu::getSubCatList($cat_id, true),
                'selected' => '',
            ];
        }
    }
    return ['output' => '', 'selected' => ''];
}

    

    public function actionAddproduct()
    {
    	 $model = new \app\models\Product();

    if ($model->load(Yii::$app->request->post())) {
            $model->file = \yii\web\UploadedFile::getInstance($model, 'file'); 
            $model->file1 = \yii\web\UploadedFile::getInstance($model, 'file1'); 
            $model->file2 = \yii\web\UploadedFile::getInstance($model, 'file2'); 
            $model->file3 = \yii\web\UploadedFile::getInstance($model, 'file3'); 
         
        if ($model->file ) {
$imagetoload = 'productos'.time();

if( $model->file->saveAs('image/products/' . $imagetoload . '.' . $model->file->extension)) 
{
$model->product_image1 = $imagetoload . '.' . $model->file->extension; 
}
}
        if ($model->file1 ) {
$imagetoload = 'products'.time();

if( $model->file1->saveAs('image/products/' . $imagetoload . '.' . $model->file1->extension)) 
{
$model->product_image2 = $imagetoload . '.' . $model->file1->extension; 
}
}
if ($model->file2 ) {
$imagetoload = 'productss'.time();

if( $model->file2->saveAs('image/products/' . $imagetoload . '.' . $model->file2->extension)) 
{
$model->product_image3 = $imagetoload . '.' . $model->file2->extension; 
}
}
if ($model->file3 ) {
$imagetoload = 'productsss'.time();

if( $model->file3->saveAs('image/products/' . $imagetoload . '.' . $model->file3->extension)) 
{
$model->product_image4 = $imagetoload . '.' . $model->file3->extension; 
}
}
        $model->save();
        return $this->redirect(['index']);
    } else {
        return $this->render('addproduct', [
            'model' => $model,
            
        ]);
    }
    }


    public function actionProductupdate($id)
    {
    	$model=\app\models\Product::findOne(['id'=>$id]);
            if($model->load(Yii::$app->request->post())){
        $model->save();
    return $this->redirect(['index']);
    } else {
    return $this->render('addproduct', [
    'model' => $model,
    ]);
    }
    }

    public function actionProductdelete($id)
    {
    	$model=\app\models\Product::findOne(['id'=>$id]);
$model->status=0;
$model->save();
return $this->redirect(['index']);
    }

    public function actionViewproduct($id)
    {
        $model= \app\models\Product::findOne(['id'=>$id]);
        return $this->render('viewproduct',['model'=>$model]);
    }

    
}

views/onlineproduct/addproduct.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

use \app\models\CategoriesMenu;
use \app\models\CategoriesSubmenu;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\models\Product */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="card">
    <div class="back-btn">
        <a href="<?=Yii::$app->homeUrl ?>?r=/onlineproduct/index"><button class="btn">Back</button></a>
    </div>
    <div class="add-title">
        <h2>Add Product</h2>
    </div>
    <hr>
<div class="product-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
        <div class="col-md-6">
        <div class="formgroup">
           <?= $form->field($model, 'categories_menu')->dropDownList(CategoriesMenu::getCategories(), ['id' => 'cat-id', 'prompt' => 'Select Category...']) ?>
</div>
</div>
<div class="col-md-6">
<div class="form-group">

    <?= $form->field($model, 'sub_menu')->widget(DepDrop::classname(), [
        'data' => CategoriesSubmenu::getSubCatList($model->categories_menu),
        'options' => ['id' => 'subcat-id', 'prompt' => 'Select Sub Category...'],
        'pluginOptions' => [
            'depends' => ['cat-id'],
            'placeholder' => 'Select Sub Category...',
            'url' => Url::to(['/onlineproduct/subcat'])
        ]
    ]) ?>
</div>
</div>
    </div>
<div class="row">
    <div class="col-md-4">
        <div class='form-group'>
             <?= $form->field($model, 'product_name')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class='form-group'>
            <?= $form->field($model, 'product_price')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class='form-group'>
            <?= $form->field($model, 'product_brand')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link1')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link2')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
             <?= $form->field($model, 'affiliate_link3')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_link4')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_price')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?= $form->field($model, 'affiliate_price1')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Sub Description</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,

    'attribute' => 'product_subdescrip',
    'options' => [
        // html attributes
        'id'=>'content'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
</div>

<div class="form-group">
    <label>Key Specification</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,

    'attribute' => 'detail',
    'options' => [
        // html attributes
        'id'=>'contento'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
</div>

<div class="form-group">
    <label>Description for Products</label>
    <?php echo froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => 'long_descrip',
    'options' => [
        // html attributes
        'id'=>'contents'
    ],
    'clientOptions' => [
        'toolbarInline' => false,
        'theme' => 'royal', //optional: dark, red, gray, royal
        'language' => 'en_gb' // optional: ar, bs, cs, da, de, en_ca, en_gb, en_us ...
    ]
]); ?>
    </div>
   

    

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
              <div class="form-group">
                
                <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/products/" . $model->product_image1;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/products/".$model->product_image1?>" />
    <?php
}
echo $form->field($model,'file')->fileInput(['maxlength'=> true]);
}
    
    ?>
            </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                
                <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file1')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/products/" . $model->product_image2;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/products/".$model->product_image2?>" />
    <?php
}
echo $form->field($model,'file1')->fileInput(['maxlength'=> true]);
}
    
    ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
               
                <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file2')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/products/" . $model->product_image3;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/products/".$model->product_image3?>" />
    <?php
}
echo $form->field($model,'file2')->fileInput(['maxlength'=> true]);
}
    
    ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                
                <?php
if($model->isNewRecord)
{

    echo $form->field($model, 'file3')->fileInput(['maxlength' => true]);
}
else
{
    $path= Yii::$app->basepath . "/web/image/products/" . $model->product_image4;
    if(file_exists($path)){
    ?><label>image</label>
    <img class="img-responsive" style="height:100px" src="<?=Yii::getAlias('@web')."/image/products/".$model->product_image4?>" />
    <?php
}
echo $form->field($model,'file3')->fileInput(['maxlength'=> true]);
}
    
    ?>
            </div>
        </div>
    </div>
    
    <?= $form->field($model, 'status')->textInput() ?>

    
    

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn']) ?>
            </div>

    <?php ActiveForm::end(); ?>

</div>

</div>
<?php
$this->registerJs($this->render('product.js'),yii\web\view::POS_READY);
?>

views/onlineproduct/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NoticesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Products';

?>


<!-- code part of the sub categories part -->
    <div class="list-grid">
    
 

    <div class=" col-md-12" >
        <div class="back-btn">
        <a href="<?=Yii::$app->homeUrl ?>?r=/site/forproduct"><button class="btn">Back</button></a>
    </div>
         <p class="edit-data" >
    <?= Html::a('Create Product', ['addproduct'], ['class' => 'btn ']) ?>
  </p>
        <div class="list-table" >
            <div class="sub-list-title">
            <h3>List of Product </h3>
            </div> 
          
     <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute'=>'categories_menu',
                'value'=>'categoriesMenu.name',
            ],
            [
                'attribute'=>'sub_menu',
                'value'=>'subMenu.name',
            ],
             // 'id',
            'product_name',
            'product_price',
            'product_brand',
            // 'product_subdescrip:ntext',
            //'affiliate_link1',
            //'affiliate_link2',
            //'affiliate_link3',
            //'affiliate_link4',
            //'long_descrip:ntext',
            //'detail:ntext',
           
            //'status',
            //'product_image1',
            //'product_image2',
            //'product_image3',
            //'product_image4',
           
            //'affiliate_price',
            //'affiliate_price1',
           


            ['class' => 'yii\grid\ActionColumn','contentOptions'=>['style'=>'width:165px'] ,'template' => '{view} {update} {delete}',

            'buttons' => [
                'view' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>View</span>", ['onlineproduct/viewproduct','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
                            'update' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>Update</span>", ['onlineproduct/productupdate','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
                            'delete' => function($url, $model, $key) {

                    return Html::a("<span class='btn  btn-xs'>Delete</span>", ['onlineproduct/productdelete','id' => $key], [
                        'title' => \yii::t('yii', 'print')
                    ]);

                }, 
         
            ]
        ],


        ],
    ]); ?>
        </div>
    </div>

</div>
<!-- end code part of the sub categories part -->

views/onlineproduct/viewproduct.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['productupdate', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['productdelete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'id',
            'product_name',
            'product_price',
            'product_brand',
            'product_subdescrip:ntext',
            'affiliate_link1',
            'affiliate_link2',
            'affiliate_link3',
            'affiliate_link4',
            'affiliate_price',
            'affiliate_price1',
            'long_descrip:ntext',
            'detail:ntext',
            'categoriesMenu.name',
            'status',
            'product_image1',
            'product_image2',
            'product_image3',
            'product_image4',
            'subMenu.name',
        ],
    ]) ?>

</div>